@startuml
title Sombra

rectangle "Fuente de luz" as Luz
rectangle Objeto
rectangle Sombra
rectangle Superficie

Luz -up-> Objeto : alcanza
Objeto -right-> Sombra : genera
Sombra -down-> Superficie : se proyecta sobre
@enduml